name: go_jek
description: A GoJek Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  connectivity: ^0.4.3+2
  async_resource: ^0.1.4
  path_provider: ^1.1.0
  shimmer: ^1.0.0
  pigment: ^1.0.3
  cached_network_image: ^1.0.0
  mockito: ^4.1.0
  test: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: git://github.com/sad1996/flutter_launcher_icons.git

flutter_icons:
  image_path: "assets/images/gojek_logo.png"
  ios: true
  android: true


flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/